### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by till** [galeone/fitbit#7]
Hey :wave: — first off, thanks for publishing this code. :) 

I had a question about how to work with the API - specially about paginating across data: Do you parse the URL in (`next`) from a list/series response to into the `*types.Pagination` struct, or is there another neat trick to achieve this?

**Comment by till** [comment]
I found your [post](https://dev.fitbit.com/build/reference/web-api/activity/get-activity-log-list/#Additional-Information), but it seems like they've since "fixed" something.

Currently doing this:

```go
	pagination := &types.Pagination{
		Offset:    0,
		AfterDate: types.FitbitDateTime{Time: start},
		Limit:     100,
		Sort:      "asc",
	}

	for {
		list, err := f.activities(pagination)
		if err != nil {
			// handle
		}

		for _, a := range list.Activities {
			activityStack[a.ActivityName] = append(activityStack[a.ActivityName], a)
		}

		if list.Pagination.Next == "" {
			break
		}

		u, err := url.Parse(list.Pagination.Next)
		if err != nil {
			// handle
		}

		if !u.Query().Has("offset") {
			break
		}

		offset, err := strconv.ParseInt(u.Query().Get("offset"), 10, 64)
		if err != nil {
			// handle
		}
		pagination.Offset = offset
	}
```

**Comment by galeone** [comment]
Let me redirect you to the usage of the pagination struct in my other project https://fitsleepinsights.app/

https://github.com/galeone/fitsleepinsights/blob/940282f8b7d26076aa00dfc49c1108a3e3a0cbf9/app/dumper.go#L265

There's a quite explicative comment there :rofl: apart from that, you can see how I handle the `Next` field and the 100 activities limitation (that's still there and I hate it)

**Comment by till** [comment]
wfm 🤣
